apiVersion: v2
name: postgresql-wrapper
description: PostgreSQL Helm wrapper for Argo CD demo
type: application
version: 0.1.0
dependencies:
  - name: postgresql
    version: 15.5.2
    repository: https://charts.bitnami.com/bitnami
